drop table if exists member CASCADE; --만들어진 테이블 있으면 일단 지우고
create table member  --member테이블 만들기
(
   id bigint generated by default as identity,
   name varchar(255),
   primary key(id)
);

insert into member(name) values('rm')